/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ControladorPartida;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Drexler Guzman
 */
public class PanelResultado extends javax.swing.JPanel {

    /**
     * Creates new form PanelResultado
     */
    private ImageIcon fondo;
    public PanelResultado() {
        initComponents();
    }

    public ImageIcon getFondo() {
        return fondo;
    }

    public void setFondo(ImageIcon fondo) {
        this.fondo = fondo;
    }


    public void paint(Graphics g){
        
        super.paint(g);
        
        fondo.paintIcon(null, g, 0, 0);
    
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/regreso.png"))); // NOI18N
        btnRegresar.setActionCommand("RegresarMenu");
        btnRegresar.setContentAreaFilled(false);
        add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 1540, 790));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    // End of variables declaration//GEN-END:variables

    public void escuchar(ControladorPartida controlador) {
        
        btnRegresar.addActionListener(controlador);
    }
}
