/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ControladorPrincial;
import javax.swing.ImageIcon;

/**
 *
 * @author 50684
 */
public class PanelMenu extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenu
     */
    public PanelMenu() {
        initComponents();
        
    }
    
    public void escuchar(ControladorPrincial controlador) {
        btnAyuda.addActionListener(controlador);
        btnControles.addActionListener(controlador);
        btnJugar.addActionListener(controlador);
        btnSalir.addActionListener(controlador);
        btnEstadisticas.addActionListener(controlador);
        btnReiniciar.addActionListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJugar = new javax.swing.JButton();
        btnControles = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setName(""); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jugar1.1.png"))); // NOI18N
        btnJugar.setActionCommand("Jugar");
        btnJugar.setContentAreaFilled(false);
        add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 390, 110));

        btnControles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controles1.1.png"))); // NOI18N
        btnControles.setActionCommand("Controles");
        btnControles.setContentAreaFilled(false);
        add(btnControles, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 210, 390, 110));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir1.1.png"))); // NOI18N
        btnSalir.setActionCommand("Salir");
        btnSalir.setContentAreaFilled(false);
        add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, 390, 110));

        btnAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ayuda1.1.png"))); // NOI18N
        btnAyuda.setActionCommand("Ayuda");
        btnAyuda.setContentAreaFilled(false);
        add(btnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 390, 110));

        btnEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Estadisticas1.1.png"))); // NOI18N
        btnEstadisticas.setActionCommand("Estadisticas");
        btnEstadisticas.setBorderPainted(false);
        btnEstadisticas.setContentAreaFilled(false);
        add(btnEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 550, -1, -1));

        btnReiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reiniciar1.1.png"))); // NOI18N
        btnReiniciar.setActionCommand("Reiniciar");
        btnReiniciar.setBorderPainted(false);
        btnReiniciar.setContentAreaFilled(false);
        add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 390, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPrincipal1.1.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnControles;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
